version: '3.8'

services:
  webhost:
    image: lab_5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379
      - REDIS_DB=1
    volumes:
      - D:\dbdata:/app/database
    ports:
      - "8000:8000"
    depends_on:
      - redis_server
  redis_server:
    image: redis
    ports:
        - "6379:6379"
  migration:
    image: lab_5_migrate
    build:
      context: .
      dockerfile: Dockerfile.migration
    volumes:
      - D:\dbdata:/app/database